version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
    depends_on:
      - post
      - comment

  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
    environment:
      - POST_DATABASE_HOST=post_db
    depends_on:
      - post_db

  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
    environment:
      - COMMENT_DATABASE_HOST=post_db
    depends_on:
      - post_db

volumes:
  post_db:

networks:
  back_net:
  front_net:
